version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres_social_network"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8573:5432"
